// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/auth.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	auth "github.com/vladdoroniuk/rose/proto_gen/auth"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetUsersProcedure is the fully-qualified name of the AuthService's GetUsers RPC.
	AuthServiceGetUsersProcedure = "/auth.v1.AuthService/GetUsers"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	authServiceServiceDescriptor        = auth.File_auth_auth_proto.Services().ByName("AuthService")
	authServiceGetUsersMethodDescriptor = authServiceServiceDescriptor.Methods().ByName("GetUsers")
)

// AuthServiceClient is a client for the auth.v1.AuthService service.
type AuthServiceClient interface {
	GetUsers(context.Context, *connect.Request[auth.EmptyRequest]) (*connect.Response[auth.GetUsersResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		getUsers: connect.NewClient[auth.EmptyRequest, auth.GetUsersResponse](
			httpClient,
			baseURL+AuthServiceGetUsersProcedure,
			connect.WithSchema(authServiceGetUsersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getUsers *connect.Client[auth.EmptyRequest, auth.GetUsersResponse]
}

// GetUsers calls auth.v1.AuthService.GetUsers.
func (c *authServiceClient) GetUsers(ctx context.Context, req *connect.Request[auth.EmptyRequest]) (*connect.Response[auth.GetUsersResponse], error) {
	return c.getUsers.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v1.AuthService service.
type AuthServiceHandler interface {
	GetUsers(context.Context, *connect.Request[auth.EmptyRequest]) (*connect.Response[auth.GetUsersResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceGetUsersHandler := connect.NewUnaryHandler(
		AuthServiceGetUsersProcedure,
		svc.GetUsers,
		connect.WithSchema(authServiceGetUsersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceGetUsersProcedure:
			authServiceGetUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetUsers(context.Context, *connect.Request[auth.EmptyRequest]) (*connect.Response[auth.GetUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.GetUsers is not implemented"))
}
