version: "3.9"

include:
  - ./commons/docker-compose.yml
  - ./services/auth/docker-compose.yml

services:
  postgres:
    image: postgres:13.13-bullseye
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net
