version: "3.9"

include:
  - ./services/api-gateway/docker-compose.yml
  - ./services/auth/docker-compose.yml

services:
  postgres:
    image: postgres:13.13-bullseye
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=kong
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./scripts/db_init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  postgres_data: {}

networks:
  postgres_net:
    external: true
