version: "3"

services:
  auth:
    container_name: rose-auth
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - keycloak

  keycloak:
    container_name: rose-keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
