version: "3"

tasks:
  colima_start:
    cmds:
      - colima start --arch linux/amd64

  docker_up:
    deps: [colima_start]
    cmds:
      - docker-compose up -d

  buf_gen:
    cmds:
      - buf generate proto
