version: "3.9"

services:
  kong-migration:
    image: kong
    container_name: kong-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: admin
    networks:
      - kong_net
      - postgres_net
    depends_on:
      - postgres

  kong-migration-up:
    image: kong
    container_name: kong-migration-up
    command: kong migrations up && kong migrations finish
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: admin
    networks:
      - kong_net
      - postgres_net
    depends_on:
      - postgres

  kong:
    image: kong:3.5.0-ubuntu
    container_name: kong
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: admin
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /var/run/kong
    ports:
      - 8000:8000
      - 8002:8002
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - kong_net
      - postgres_net
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
    depends_on:
      - postgres

volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong_net: {}
