version: "3"

vars:
  SERVICE_NAME: api-gateway

dotenv: [".env"]

tasks:
  go_build:
    cmds:
      - go build -o ./bin/{{.SERVICE_NAME}}

  go_run:
    deps: [go_build]
    cmds:
      - ./bin/{{.SERVICE_NAME}}
